apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: dwh-etl-daily
spec:
  schedule: "5 * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  timezone: Asia/Jerusalem
  workflowSpec:
    entrypoint: diamond
    templates:
    - name: echo
      inputs:
        parameters:
        - name: message
      container:
        image: alpine:3.7
        command: [echo, "{{inputs.parameters.message}}"]
    - name: echo-thrice
      inputs:
        parameters:
        - name: message
      steps:
      - - name: echo
          template: echo
          arguments:
            parameters:
            - {name: message, value: "{{inputs.parameters.message}}{{item}}"}
          withItems: [1,2,3]
    - name: diamond
      dag:
        tasks:
        - name: A
          template: echo-thrice
          arguments:
            parameters: [{name: message, value: A}]
        - name: B
          depends: "A"
          template: echo-thrice
          arguments:
            parameters: [{name: message, value: B}]
        - name: C
          depends: "A"
          template: echo-thrice
          arguments:
            parameters: [{name: message, value: C}]
        - name: D
          depends: "B && C"
          template: echo-thrice
          arguments:
            parameters: [{name: message, value: D}]
